project_id = "fqqwdswevtwrgkornjqo"

[functions.validate-shareasale]
verify_jwt = false

[functions.sync-shareasale]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.scan-affiliate-links]
verify_jwt = false

[functions.store-awin-credentials]
verify_jwt = false
